/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_twitter_android_fibonaccinative_FibLib */

#ifndef _Included_com_twitter_android_fibonaccinative_FibLib
#define _Included_com_twitter_android_fibonaccinative_FibLib
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
